name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Cache
    - uses: actions/cache@v2
      with:
        path: | 
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore ./Bobedre/Bobedre.sln
    - name: Build
      run: dotnet build ./Bobedre/Bobedre.sln --no-restore
    - name: Test
      run: dotnet test ./Bobedre/Bobedre.sln --no-build --verbosity normal
